# top level stuff you probably don't need to touch
highlighter: rouge
#markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://djbb7.github.io/
baseurl: /
title: Daniel Bruzual - Software Architect, Computer Engineer
author: Daniel Bruzual
description: Computer Engineer, Software Architect.
avatar: profile.jpg
email: danielbruzual@gmail.com
github: djbb7 # username
twitter: danbruzual
telegram: dbruzual
linkedin: danbruzual
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-84288459-1


# needed for travis-ci build
exclude: [vendor]
